import { ArrowLeft, FlaskConical, Keyboard, ShieldCheck, Sparkles } from "lucide-react";
import { EASTER_EGGS, EGG_GROUPS } from "../components/EasterEggLayer";

export default function AfterHoursPage({ onBack }) {
  const groups = Object.keys(EGG_GROUPS).map((id) => ({ id, ...EGG_GROUPS[id], eggs: EASTER_EGGS.filter((egg) => egg.category === id) }));
  return (
    <main className="min-h-screen bg-[#F5F3EC] text-[#17251F]">
      <header className="border-b border-[#DDE1D9] bg-[#FFFDF8]/95 backdrop-blur"><div className="mx-auto flex max-w-5xl items-center gap-3 px-4 py-3 sm:px-6"><a href="/" className="flex h-9 w-9 items-center justify-center rounded-full text-[#59645E] hover:bg-[#EEF1EA]" aria-label="홈으로"><ArrowLeft size={18} /></a><div><p className="text-[11px] font-semibold tracking-[0.1em] text-[#17866D]">UNOFFICIAL / AFTER HOURS</p><h1 className="text-lg font-semibold tracking-[-0.03em]">콕폼 비공식 이스터에그 60</h1></div></div></header>
      <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-12">
        <section className="grid gap-5 rounded-2xl border border-[#B7DCC8] bg-[#EAF6EF] p-5 sm:grid-cols-[1fr_auto] sm:p-7"><div><div className="flex items-center gap-2 text-[#0B4D3D]"><FlaskConical size={19} /><p className="text-sm font-semibold">발견해도 데이터는 건드리지 않습니다.</p></div><h2 className="mt-3 text-2xl font-semibold tracking-[-0.04em] sm:text-3xl">업무 중 잠깐 열어보는, 콕폼의 작은 실험들.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[#355C45]">모든 항목은 이 브라우저의 로컬 설정으로만 저장됩니다. 응답 원문, 암호화 키, 로그인 권한, 폼 구조, 서버 저장값에는 접근하거나 변경하지 않습니다.</p></div><Sparkles className="hidden text-[#17866D] sm:block" size={34} /></section>
        <section className="mt-8 grid gap-4 md:grid-cols-3"><article className="rounded-xl border border-[#DDE1D9] bg-[#FFFDF8] p-4"><Keyboard className="text-[#17866D]" size={18} /><h2 className="mt-3 font-semibold">여는 법</h2><p className="mt-2 text-sm leading-6 text-[#59645E]">입력칸 밖에서 <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>E</kbd>를 누르거나, <code>cokform</code>을 차례로 입력하세요.</p></article><article className="rounded-xl border border-[#DDE1D9] bg-[#FFFDF8] p-4"><ShieldCheck className="text-[#17866D]" size={18} /><h2 className="mt-3 font-semibold">해제하는 법</h2><p className="mt-2 text-sm leading-6 text-[#59645E]">같은 항목을 한 번 더 누르면 해제됩니다. 실험실의 <strong>전부 해제</strong>는 이 기기의 설정만 초기화합니다.</p></article><article className="rounded-xl border border-[#DDE1D9] bg-[#FFFDF8] p-4"><Sparkles className="text-[#17866D]" size={18} /><h2 className="mt-3 font-semibold">움직임 원칙</h2><p className="mt-2 text-sm leading-6 text-[#59645E]">운영체제의 동작 줄이기 설정을 존중합니다. 공개 폼에서도 열리지만 제출 경험을 가로막지 않습니다.</p></article></section>
        <section className="mt-10"><p className="text-[11px] font-semibold tracking-[0.1em] text-[#17866D]">CATALOGUE / 60</p><h2 className="mt-1 text-2xl font-semibold tracking-[-0.04em]">전체 목록</h2><p className="mt-2 text-sm leading-6 text-[#59645E]">각 항목은 같은 카테고리 안에서 하나씩만 적용됩니다. 따라서 화면이 과하게 섞이지 않습니다.</p><div className="mt-6 space-y-8">{groups.map((group) => <section key={group.id} id={group.id} className="scroll-mt-6"><div className="flex items-end justify-between border-b border-[#DDE1D9] pb-3"><div><p className="text-[11px] font-semibold tracking-[0.1em] text-[#17866D]">{group.label}</p><h3 className="mt-1 text-xl font-semibold tracking-[-0.03em]">{group.note}</h3></div><span className="text-sm text-[#78837C]">{group.eggs.length}개</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{group.eggs.map((egg) => <article key={egg.id} className="rounded-xl border border-[#E1E5DE] bg-[#FFFDF8] p-3"><div className="flex gap-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#EEF1EA] text-[11px] font-semibold text-[#0B4D3D]">{egg.order}</span><div><h4 className="text-sm font-semibold">{egg.title}</h4><p className="mt-1 text-xs leading-5 text-[#59645E]">{egg.description}</p></div></div></article>)}</div></section>)}</div>
        </section>
        <footer className="mt-12 border-t border-[#DDE1D9] pt-5 text-sm leading-6 text-[#59645E]"><strong className="text-[#17251F]">운영 메모.</strong> 이 문서는 콕폼 공식 기능 명세나 개인정보처리방침이 아닙니다. 실험 항목을 서비스 기본값으로 삼지 말고, 사용자가 직접 발동한 경우에만 적용하세요.</footer>
      </div>
    </main>
  );
}
