-- Secure submission gateway (2026-08-18)
-- Public form responses are accepted only through the Edge Function. The function
-- validates the E2EE envelope, form availability, origin and a short-lived,
-- privacy-preserving request-rate fingerprint before inserting with service_role.

-- Clients must no longer write arbitrary rows directly to responses. This closes
-- the public PostgREST insert endpoint that could otherwise be spammed or used to
-- consume a form owner's pilot quota.
drop policy if exists "responses public insert" on public.responses;

-- Owners may import an encrypted recovery bundle for a form they own. Plaintext
-- answers are never allowed through this owner-only recovery path.
drop policy if exists "responses owner encrypted insert" on public.responses;
create policy "responses owner encrypted insert" on public.responses
for insert
with check (
  exists (
    select 1 from public.forms f
    where f.id = responses.form_id and f.owner = auth.uid()
  )
  and jsonb_typeof(answers) = 'object'
  and (answers ->> 'version') in ('1', '2')
  and coalesce(answers ->> 'ciphertext', '') <> ''
  and coalesce(answers ->> 'iv', '') <> ''
);

-- A short-lived, keyed fingerprint is used only for anti-abuse rate limiting.
-- No raw IP address, email address, answer, or browser identifier is stored.
create table if not exists public.cokform_response_rate_limits (
  form_id text not null references public.forms(id) on delete cascade,
  fingerprint text not null check (length(fingerprint) = 64),
  bucket_started_at timestamptz not null,
  attempt_count smallint not null default 1 check (attempt_count between 1 and 12),
  created_at timestamptz not null default now(),
  primary key (form_id, fingerprint, bucket_started_at)
);

alter table public.cokform_response_rate_limits enable row level security;

-- Atomically allow at most twelve submission attempts per form and keyed client
-- fingerprint in each ten-minute bucket. Only the server-side Edge Function may
-- execute this function; anonymous and authenticated browser clients cannot call it.
create or replace function public.claim_cokform_response_rate_limit(
  p_form_id text,
  p_fingerprint text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  bucket_start timestamptz;
  accepted_count smallint;
begin
  if p_form_id is null or p_fingerprint is null or length(p_fingerprint) <> 64 then
    return false;
  end if;

  bucket_start := date_trunc('minute', now())
    - ((extract(minute from now())::integer % 10) * interval '1 minute');

  insert into public.cokform_response_rate_limits (
    form_id,
    fingerprint,
    bucket_started_at,
    attempt_count
  ) values (
    p_form_id,
    p_fingerprint,
    bucket_start,
    1
  )
  on conflict (form_id, fingerprint, bucket_started_at) do update
    set attempt_count = public.cokform_response_rate_limits.attempt_count + 1
    where public.cokform_response_rate_limits.attempt_count < 12
  returning attempt_count into accepted_count;

  return found and accepted_count <= 12;
end;
$$;

revoke all on function public.claim_cokform_response_rate_limit(text, text) from public, anon, authenticated;
grant execute on function public.claim_cokform_response_rate_limit(text, text) to service_role;

-- Keep anti-abuse metadata short-lived. The fingerprint is already HMAC-derived
-- server-side and is automatically purged after two hours.
select cron.unschedule(jobid)
from cron.job
where jobname = 'cokform-purge-response-rate-limits';

select cron.schedule(
  'cokform-purge-response-rate-limits',
  '7 * * * *',
  $$delete from public.cokform_response_rate_limits where bucket_started_at < now() - interval '2 hours';$$
);

-- Form view analytics existed in the client but had not been deployed in the
-- production schema. This table stores only an opaque browser-local visitor ID.
create table if not exists public.form_views (
  id bigint generated by default as identity primary key,
  form_id text not null references public.forms(id) on delete cascade,
  visitor_id text not null,
  viewed_at timestamptz not null default now(),
  unique (form_id, visitor_id)
);

alter table public.form_views enable row level security;

drop policy if exists "form views public insert" on public.form_views;
create policy "form views public insert" on public.form_views
for insert
with check (
  exists (select 1 from public.form_public p where p.id = form_views.form_id)
);

drop policy if exists "form views owner read" on public.form_views;
create policy "form views owner read" on public.form_views
for select
using (
  exists (select 1 from public.forms f where f.id = form_views.form_id and f.owner = auth.uid())
);

create index if not exists form_views_form_id_viewed_at_idx
  on public.form_views (form_id, viewed_at desc);

-- SECURITY DEFINER helper functions must never be callable from a browser role.
revoke all on function public.claim_cokform_response_rate_limit(text, text) from public, anon, authenticated;

-- The Turnstile secret is provisioned separately into Supabase Vault and is
-- never committed to this repository. Only an Edge Function using service_role
-- may read it while verifying a submitted Turnstile token.
create or replace function public.read_cokform_turnstile_secret()
returns text
language plpgsql
security definer
set search_path = public, vault
as $$
declare
  secret_value text;
begin
  select decrypted_secret
    into secret_value
    from vault.decrypted_secrets
   where name = 'cokform_turnstile_secret'
   limit 1;
  return secret_value;
end;
$$;

revoke all on function public.read_cokform_turnstile_secret() from public, anon, authenticated;
grant execute on function public.read_cokform_turnstile_secret() to service_role;
