-- Privacy retention and audit controls for Cokform.
-- Response plaintext is never stored in this table: answers remains browser-encrypted.

alter table public.responses add column if not exists expires_at timestamptz;

update public.responses r
set expires_at = r.submitted_at + make_interval(
  days => greatest(1, least(3650, coalesce((f.data->'form'->'settings'->>'retentionDays')::int, 180)))
)
from public.forms f
where f.id = r.form_id
  and r.expires_at is null;

alter table public.responses alter column expires_at set not null;
create index if not exists responses_expires_at_idx on public.responses (expires_at);

create or replace function public.set_cokform_response_expiry()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare retention_days integer;
begin
  select greatest(1, least(3650, coalesce((data->'form'->'settings'->>'retentionDays')::int, 180)))
    into retention_days
  from public.forms
  where id = new.form_id;

  new.expires_at := coalesce(new.submitted_at, now()) + make_interval(days => coalesce(retention_days, 180));
  return new;
end;
$$;

drop trigger if exists responses_set_expiry on public.responses;
create trigger responses_set_expiry
before insert on public.responses
for each row execute function public.set_cokform_response_expiry();

create table if not exists public.form_audit_events (
  id bigint generated by default as identity primary key,
  form_id text not null references public.forms(id) on delete cascade,
  event_type text not null check (event_type in ('export', 'responses_deleted', 'retention_purge')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.form_audit_events enable row level security;

drop policy if exists "form audit owner select" on public.form_audit_events;
create policy "form audit owner select" on public.form_audit_events for select using (
  exists (select 1 from public.forms f where f.id = form_audit_events.form_id and f.owner = auth.uid())
);
drop policy if exists "form audit owner insert" on public.form_audit_events;
create policy "form audit owner insert" on public.form_audit_events for insert with check (
  exists (select 1 from public.forms f where f.id = form_audit_events.form_id and f.owner = auth.uid())
);
create index if not exists form_audit_events_form_id_created_at_idx
  on public.form_audit_events (form_id, created_at desc);

create or replace function public.purge_expired_cokform_responses()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare deleted_count bigint;
begin
  with expired as (
    delete from public.responses
    where expires_at <= now()
    returning form_id
  ), logged as (
    insert into public.form_audit_events (form_id, event_type, metadata)
    select form_id, 'retention_purge', jsonb_build_object('responseCount', count(*))
    from expired
    group by form_id
  )
  select count(*) into deleted_count from expired;

  return deleted_count;
end;
$$;

revoke all on function public.set_cokform_response_expiry() from public, anon, authenticated;
revoke all on function public.purge_expired_cokform_responses() from public, anon, authenticated;
grant execute on function public.purge_expired_cokform_responses() to service_role;

-- Run once daily within Postgres. The job stores only a function call, not response data.
create extension if not exists pg_cron with schema pg_catalog;
select cron.unschedule(jobid) from cron.job where jobname = 'cokform-purge-expired-responses';
select cron.schedule(
  'cokform-purge-expired-responses',
  '17 20 * * *',
  $$select public.purge_expired_cokform_responses();$$
);
